apiVersion: v1 
kind: Service
metadata:
  name: service
  labels:
    project: roboshop
    purpose: helm-practice
spec:
  selector:
    project: roboshop
    puprose: helm-practice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80